import { Project, User, Comment, RatingSummary, DiscoverySection } from '@/types/bmdb';

// Mock data for development - replace with actual API calls

export const mockUsers: User[] = [
  {
    id: '1',
    username: 'sofia_chen',
    displayName: 'Sofia Chen',
    email: 'sofia@email.com',
    bio: 'Award-winning director specializing in narrative shorts and documentaries. USC Film School graduate.',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop',
    location: 'Los Angeles, CA',
    website: 'https://sofiachen.com',
    createdAt: '2023-01-15',
  },
  {
    id: '2',
    username: 'marcus_rivera',
    displayName: 'Marcus Rivera',
    email: 'marcus@email.com',
    bio: 'Cinematographer and visual storyteller. Known for creating atmospheric, emotionally driven imagery.',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop',
    location: 'New York, NY',
    createdAt: '2023-02-20',
  },
  {
    id: '3',
    username: 'emma_wright',
    displayName: 'Emma Wright',
    email: 'emma@email.com',
    bio: 'Actor and screenwriter with a passion for character-driven narratives.',
    avatarUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop',
    location: 'London, UK',
    createdAt: '2023-03-10',
  },
];

export const mockProjects: Project[] = [
  {
    id: '1',
    slug: 'the-last-light',
    title: 'The Last Light',
    tagline: 'Some distances cannot be measured in miles.',
    synopsis: 'A grieving lighthouse keeper forms an unlikely bond with a mysterious visitor who washes ashore during a violent storm. As they wait for rescue, secrets from both their pasts begin to surface.',
    posterUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=600&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=1920&h=1080&fit=crop',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    projectType: 'SHORT_FILM',
    status: 'PUBLISHED',
    year: 2024,
    runtime: 18,
    organization: 'USC School of Cinematic Arts',
    location: 'Los Angeles, CA',
    genres: ['Drama', 'Mystery'],
    ownerId: '1',
    owner: mockUsers[0],
    averageRating: 8.7,
    ratingCount: 124,
    createdAt: '2024-01-10',
    publishedAt: '2024-02-15',
  },
  {
    id: '2',
    slug: 'echoes-in-the-dark',
    title: 'Echoes in the Dark',
    tagline: 'Memory is a prison we build ourselves.',
    synopsis: 'An aging musician loses their hearing and must confront the ghosts of their past through the music they can no longer hear. A meditation on loss, legacy, and the power of artistic expression.',
    posterUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=400&h=600&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1920&h=1080&fit=crop',
    projectType: 'DOCUMENTARY',
    status: 'PUBLISHED',
    year: 2024,
    runtime: 45,
    organization: 'NYU Tisch School of the Arts',
    location: 'New York, NY',
    genres: ['Documentary', 'Music'],
    ownerId: '2',
    owner: mockUsers[1],
    averageRating: 9.2,
    ratingCount: 89,
    createdAt: '2024-02-01',
    publishedAt: '2024-03-20',
  },
  {
    id: '3',
    slug: 'between-frames',
    title: 'Between Frames',
    tagline: 'What happens when the camera stops rolling?',
    synopsis: 'A behind-the-scenes look at the making of an independent film turns into an unexpected exploration of the blurred lines between art and life, fiction and reality.',
    posterUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=1920&h=1080&fit=crop',
    projectType: 'EXPERIMENTAL',
    status: 'PUBLISHED',
    year: 2023,
    runtime: 22,
    organization: 'UCLA School of Theater, Film and Television',
    location: 'Los Angeles, CA',
    genres: ['Experimental', 'Drama'],
    ownerId: '3',
    owner: mockUsers[2],
    averageRating: 7.9,
    ratingCount: 56,
    createdAt: '2023-11-15',
    publishedAt: '2024-01-05',
  },
  {
    id: '4',
    slug: 'silent-streets',
    title: 'Silent Streets',
    tagline: 'In the city that never sleeps, everyone has a secret.',
    synopsis: 'Three strangers in New York City find their lives intertwined over the course of one sleepless night, each carrying burdens they cannot share.',
    posterUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=400&h=600&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=1920&h=1080&fit=crop',
    projectType: 'SHORT_FILM',
    status: 'PUBLISHED',
    year: 2024,
    runtime: 24,
    organization: 'Columbia University',
    location: 'New York, NY',
    genres: ['Drama', 'Noir'],
    ownerId: '1',
    owner: mockUsers[0],
    averageRating: 8.4,
    ratingCount: 203,
    createdAt: '2024-03-01',
    publishedAt: '2024-04-10',
  },
  {
    id: '5',
    slug: 'red-thread',
    title: 'Red Thread',
    tagline: 'Fate has a way of finding us.',
    synopsis: 'A young woman discovers an old journal in a vintage shop that seems to predict her future, leading her on a journey through time and memory.',
    posterUrl: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=400&h=600&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1518834107812-67b0b7c58434?w=1920&h=1080&fit=crop',
    projectType: 'SHORT_FILM',
    status: 'PUBLISHED',
    year: 2024,
    runtime: 15,
    organization: 'AFI Conservatory',
    location: 'Los Angeles, CA',
    genres: ['Fantasy', 'Romance'],
    ownerId: '3',
    owner: mockUsers[2],
    averageRating: 8.1,
    ratingCount: 78,
    createdAt: '2024-04-05',
    publishedAt: '2024-05-01',
  },
  {
    id: '6',
    slug: 'the-weight-of-water',
    title: 'The Weight of Water',
    tagline: 'Some burdens are meant to be carried together.',
    synopsis: 'A competitive swimmer struggling with anxiety forms an unexpected friendship with their elderly neighbor, learning that strength comes in many forms.',
    posterUrl: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=400&h=600&fit=crop',
    backdropUrl: 'https://images.unsplash.com/photo-1530549387789-4c1017266635?w=1920&h=1080&fit=crop',
    projectType: 'STUDENT_FILM',
    status: 'PUBLISHED',
    year: 2024,
    runtime: 28,
    organization: 'CalArts',
    location: 'Valencia, CA',
    genres: ['Drama', 'Sports'],
    ownerId: '2',
    owner: mockUsers[1],
    averageRating: 9.0,
    ratingCount: 142,
    createdAt: '2024-02-20',
    publishedAt: '2024-03-15',
  },
];

export const mockComments: Comment[] = [
  {
    id: '1',
    projectId: '1',
    userId: '2',
    user: mockUsers[1],
    content: 'Exceptional cinematography. The use of natural light in the lighthouse scenes creates an atmosphere that perfectly complements the narrative tension. The director shows remarkable restraint in letting moments breathe.',
    createdAt: '2024-02-20T14:30:00Z',
    updatedAt: '2024-02-20T14:30:00Z',
  },
  {
    id: '2',
    projectId: '1',
    userId: '3',
    user: mockUsers[2],
    content: 'The performances here are truly compelling. Both leads bring such depth to their characters, and the chemistry between them feels authentic and earned. Looking forward to seeing more from this team.',
    createdAt: '2024-02-21T09:15:00Z',
    updatedAt: '2024-02-21T09:15:00Z',
  },
];

export const mockDiscoverySections: DiscoverySection[] = [
  {
    id: 'trending',
    title: 'Trending Now',
    subtitle: 'Most discussed this week',
    projects: [mockProjects[3], mockProjects[0], mockProjects[5]],
  },
  {
    id: 'top-rated',
    title: 'Top Rated',
    subtitle: 'Highest community ratings',
    projects: [mockProjects[1], mockProjects[5], mockProjects[0]],
  },
  {
    id: 'new-notable',
    title: 'New & Notable',
    subtitle: 'Recently published with rising acclaim',
    projects: [mockProjects[4], mockProjects[3], mockProjects[2]],
  },
  {
    id: 'recently-added',
    title: 'Recently Added',
    subtitle: 'Fresh submissions from the community',
    projects: [mockProjects[4], mockProjects[5], mockProjects[3]],
  },
];

export const mockRatingSummary: RatingSummary = {
  projectId: '1',
  averageRating: 8.7,
  ratingCount: 124,
  distribution: {
    10: 18,
    9: 32,
    8: 45,
    7: 20,
    6: 6,
    5: 2,
    4: 1,
    3: 0,
    2: 0,
    1: 0,
  },
};
